apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: list-prs-template
  title: List Open Pull Requests
  description: Lists all open pull requests for a repository with details like author, date, title, etc.
  tags:
    - git
    - pr
    - github
spec:
  owner: platform-team
  type: service
  
  parameters:
    - title: Repository Information
      required:
        - owner
        - repo
      properties:
        owner:
          title: Repository Owner
          type: string
          description: 'GitHub organization or username (e.g., r-reis)'
          ui:autofocus: true
          
        repo:
          title: Repository Name
          type: string
          description: 'Repository name (e.g., backstage-plugins)'
          
        state:
          title: PR State
          type: string
          description: 'Filter by PR state'
          enum:
            - open
            - closed
            - all
          default: open
          
        outputFormat:
          title: Output Format
          type: string
          description: 'Format of the output file'
          enum:
            - markdown
            - json
          default: markdown

  steps:
    - id: create-reports
      name: Create PR List Reports
      action: fetch:template
      input:
        url: ./skeleton
        values:
          owner: ${{ parameters.owner }}
          repo: ${{ parameters.repo }}
          state: ${{ parameters.state }}
          apiUrl: https://api.github.com/repos/${{ parameters.owner }}/${{ parameters.repo }}/pulls?state=${{ parameters.state }}&per_page=100
          githubUrl: https://github.com/${{ parameters.owner }}/${{ parameters.repo }}/pulls

  output:
    links:
      - title: View PRs on GitHub
        url: https://github.com/${{ parameters.owner }}/${{ parameters.repo }}/pulls?q=is:pr+is:${{ parameters.state }}
      - title: GitHub API Endpoint
        url: https://api.github.com/repos/${{ parameters.owner }}/${{ parameters.repo }}/pulls?state=${{ parameters.state }}
    text:
      - title: Repository
        content: ${{ parameters.owner }}/${{ parameters.repo }}
      - title: PR State Filter
        content: ${{ parameters.state }}
      - title: Generated Files
        content: |
          The template has generated two files in your workspace:
          
          1. **pr-list.html** - Interactive HTML report
             - Open this file in your web browser
             - It will automatically fetch and display pull requests
             - For private repositories, enter your GitHub token when prompted
             
          2. **pr-list.md** - Markdown documentation
             - Contains API endpoint information and usage examples
             
          Both files are located in the workspace directory created by this template.
