apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: list-prs-template
  title: List Open Pull Requests
  description: Lists all open pull requests for a repository with details like author, date, title, etc.
  tags:
    - git
    - pr
    - github
spec:
  owner: platform-team
  type: service
  
  parameters:
    - title: Repository Information
      required:
        - owner
        - repo
      properties:
        owner:
          title: Repository Owner
          type: string
          description: 'GitHub organization or username (e.g., r-reis)'
          ui:autofocus: true
          
        repo:
          title: Repository Name
          type: string
          description: 'Repository name (e.g., backstage-plugins)'
          
        state:
          title: PR State
          type: string
          description: 'Filter by PR state'
          enum:
            - open
            - closed
            - all
          default: open
          
  steps:
    - id: create-reports
      name: Create PR List Reports
      action: fetch:template
      input:
        url: ./skeleton
        values:
          owner: ${{ parameters.owner }}
          repo: ${{ parameters.repo }}
          state: ${{ parameters.state }}
          apiUrl: https://api.github.com/repos/${{ parameters.owner }}/${{ parameters.repo }}/pulls?state=${{ parameters.state }}&per_page=100
          githubUrl: https://github.com/${{ parameters.owner }}/${{ parameters.repo }}/pulls

  output:
    links:
      - title: View PRs on GitHub
        url: https://github.com/${{ parameters.owner }}/${{ parameters.repo }}/pulls?q=is:pr+is:${{ parameters.state }}
      - title: GitHub API Endpoint
        url: https://api.github.com/repos/${{ parameters.owner }}/${{ parameters.repo }}/pulls?state=${{ parameters.state }}
    text:
      - title: Repository
        content: ${{ parameters.owner }}/${{ parameters.repo }}
      - title: PR State Filter
        content: ${{ parameters.state }}
      - title: 📁 Generated Files
        content: |
          The template has created two files:
          • pr-list.html - Interactive HTML report (open in browser)
          • pr-list.md - Markdown documentation with API examples
          
      - title: 🔍 How to Access Files in Backstage UI
        content: |
          **Method 1: Task Output Download (Recommended)**
          
          After the task completes, look for one of these options in the task output screen:
          • A "Download" button or link
          • A "Download Workspace" button
          • A "View Files" or "Browse Workspace" option
          • Files listed in the task output that you can click to download
          
          Once downloaded, extract the ZIP file and open `pr-list.html` in your browser.
          
          **Method 2: Task Logs/Workspace**
          
          Some Backstage installations show workspace files in:
          • The task execution logs
          • A "Workspace" tab in the task details
          • File browser in the task output
          
          **Method 3: Direct File Access**
          
          If you have access to the Backstage backend, files are typically stored in:
          `/tmp/backstage-workspace/[task-id]/`
          
          You can also check the task logs for the exact workspace path.
          
      - title: 💡 Using the HTML Report
        content: |
          Once you have `pr-list.html`:
          1. Open it in any modern web browser (Chrome, Firefox, Safari, Edge)
          2. The page will automatically fetch PRs from GitHub API
          3. For private repositories, enter your GitHub token in the input field
          4. Click "Refresh PR List" to update the data
          
          The HTML file is self-contained and works offline (it fetches data from GitHub when opened).
