apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: open-pr-template
  title: Open Pull Request
  description: Opens a PR with a hello world file in any repository
  tags:
    - git
    - pr
spec:
  owner: platform-team
  type: service
  
  parameters:
    - title: Pull Request Information
      required:
        - username
        - targetRepo
        - prTitle
      properties:
        username:
          title: Your Username
          type: string
          description: Your GitHub/GitLab username
          ui:autofocus: true
        
        targetRepo:
          title: Target Repository
          type: string
          description: 'Repository in format: org/repo or github.com/org/repo or https://github.com/org/repo'
          ui:placeholder: 'my-org/my-repo'
        
        prTitle:
          title: PR Title
          type: string
          default: 'Add hello world file'
        
        prDescription:
          title: PR Description
          type: string
          ui:widget: textarea
          default: 'This PR adds a hello world file'
          
        branchName:
          title: Branch Name
          type: string
          default: 'add-hello-world'

  steps:
    - id: fetch-base
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          username: ${{ parameters.username }}

    - id: debug-repo-url
      name: Debug Repository URL
      action: script:execute
      input:
        script: |
          const input = '${{ parameters.targetRepo }}';
          const cleaned = input
            .replace(/^https?:\/\//, '')
            .replace(/^github\.com\//, '');
          const parts = cleaned.split('/').filter(p => p);
          const owner = parts[0] || 'MISSING';
          const repo = parts[1] || 'MISSING';
          const repoUrl1 = `github.com?owner=${owner}&repo=${repo}`;
          const repoUrl2 = `github.com?repo=${repo}&owner=${owner}`;
          console.log('=== Repository URL Debug ===');
          console.log(`Input: ${input}`);
          console.log(`Cleaned: ${cleaned}`);
          console.log(`Owner: ${owner}, Repo: ${repo}`);
          console.log(`Format 1: ${repoUrl1}`);
          console.log(`Format 2: ${repoUrl2}`);

    - id: publish
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=${{ ((parameters.targetRepo | replace('https://', '') | replace('http://', '') | replace('github.com/', '') | split('/')) | reject('equalto', ''))[1] }}&owner=${{ ((parameters.targetRepo | replace('https://', '') | replace('http://', '') | replace('github.com/', '') | split('/')) | reject('equalto', ''))[0] }}
        branchName: ${{ parameters.branchName }}
        title: ${{ parameters.prTitle }}
        description: ${{ parameters.prDescription }}
        gitAuthorName: ${{ parameters.username }}
        gitAuthorEmail: ${{ parameters.username }}@example.com

  output:
    links:
      - title: View Pull Request
        url: ${{ steps.publish.output.remoteUrl }}
