apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: open-pr-template
  title: Request Pull Request
  description: Creates a PR request that needs approval before opening the actual PR
  tags:
    - git
    - pr
    - approval
spec:
  owner: platform-team
  type: service
  
  parameters:
    - title: Pull Request Information
      required:
        - username
        - owner
        - repo
        - prTitle
      properties:
        username:
          title: Your Username
          type: string
          description: Your GitHub/GitLab username
          ui:autofocus: true
        
        owner:
          title: Repository Owner
          type: string
          description: 'GitHub organization or username (e.g., r-reis)'
          ui:autofocus: true
          
        repo:
          title: Repository Name
          type: string
          description: 'Repository name (e.g., backstage-plugins)'
        
        prTitle:
          title: PR Title
          type: string
          default: 'Add hello world file'
        
        prDescription:
          title: PR Description
          type: string
          ui:widget: textarea
          default: 'This PR adds a hello world file'
          
        branchName:
          title: Branch Name
          type: string
          default: 'add-hello-world'

  steps:
    - id: fetch-base
      name: Fetch Template Files
      action: fetch:template
      input:
        url: ./skeleton
        values:
          username: ${{ parameters.username }}

    - id: register
      name: Create PR Request in Catalog
      action: catalog:write
      input:
        entity:
          apiVersion: backstage.io/v1alpha1
          kind: Component
          metadata:
            name: pr-request-${{ parameters.owner }}-${{ parameters.repo }}-${{ parameters.branchName }}
            namespace: default
            title: "[PENDING] ${{ parameters.prTitle }}"
            description: ${{ parameters.prDescription }}
            annotations:
              github.com/project-slug: ${{ parameters.owner }}/${{ parameters.repo }}
              backstage.io/approval-status: pending
              backstage.io/pr-branch: ${{ parameters.branchName }}
              backstage.io/pr-title: ${{ parameters.prTitle }}
              backstage.io/pr-description: ${{ parameters.prDescription }}
              backstage.io/requested-by: ${{ parameters.username }}
          spec:
            type: pr-request
            lifecycle: experimental
            owner: ${{ parameters.username }}
            system: pull-requests

  output:
    links:
      - title: View PR Request in Catalog
        url: /catalog/default/component/pr-request-${{ parameters.owner }}-${{ parameters.repo }}-${{ parameters.branchName }}
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
    text:
      - title: PR Request Created
        content: |
          Your PR request has been created and is **pending approval**.

          **Request Details:**
          - Repository: ${{ parameters.owner }}/${{ parameters.repo }}
          - Branch: ${{ parameters.branchName }}
          - Title: ${{ parameters.prTitle }}
          - Requested by: ${{ parameters.username }}

          **Next Steps:**
          1. A reviewer will approve or reject this request
          2. Once approved, the actual GitHub PR will be created
          3. You'll be notified when the PR is created

          **Entity Reference:** ${{ steps.register.output.entityRef }}

          You can track the status of your request in the catalog.
