apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: open-pr-template
  title: Open Pull Request
  description: Opens a PR with a hello world file in any repository
  tags:
    - git
    - pr
spec:
  owner: platform-team
  type: service
  
  parameters:
    - title: Pull Request Information
      required:
        - username
        - owner
        - repo
        - prTitle
      properties:
        username:
          title: Your Username
          type: string
          description: Your GitHub/GitLab username
          ui:autofocus: true
        
        owner:
          title: Repository Owner
          type: string
          description: 'GitHub organization or username (e.g., r-reis)'
          ui:autofocus: true
          
        repo:
          title: Repository Name
          type: string
          description: 'Repository name (e.g., backstage-plugins)'
        
        prTitle:
          title: PR Title
          type: string
          default: 'Add hello world file'
        
        prDescription:
          title: PR Description
          type: string
          ui:widget: textarea
          default: 'This PR adds a hello world file'
          
        branchName:
          title: Branch Name
          type: string
          default: 'add-hello-world'

  steps:
    - id: fetch-base
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          username: ${{ parameters.username }}

    - id: publish
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=${{ parameters.owner }}&repo=${{ parameters.repo }}
        branchName: ${{ parameters.branchName }}
        title: ${{ parameters.prTitle }}
        description: ${{ parameters.prDescription }}
        gitAuthorName: ${{ parameters.username }}
        gitAuthorEmail: ${{ parameters.username }}@example.com

    - id: catalog-write
      name: Write Catalog Entity
      action: write:file
      input:
        path: ./catalog-info.yaml
        content: |
          apiVersion: backstage.io/v1alpha1
          kind: Component
          metadata:
            name: pr-${{ parameters.owner }}-${{ parameters.repo }}-${{ parameters.branchName }}
            title: ${{ parameters.prTitle }}
            description: ${{ parameters.prDescription }}
            annotations:
              github.com/project-slug: ${{ parameters.owner }}/${{ parameters.repo }}
              github.com/pull-request-url: ${{ steps.publish.output.remoteUrl }}
          spec:
            type: pull-request
            lifecycle: production
            owner: ${{ parameters.username }}
            links:
              - url: ${{ steps.publish.output.remoteUrl }}
                title: View on GitHub
                icon: github

    - id: register
      name: Register Entity in Catalog
      action: catalog:write
      input:
        filePath: ./catalog-info.yaml

  output:
    links:
      - title: View Pull Request
        url: ${{ steps.publish.output.remoteUrl }}
      - title: View in Catalog
        url: /catalog/default/component/pr-${{ parameters.owner }}-${{ parameters.repo }}-${{ parameters.branchName }}
    text:
      - title: Catalog Registration
        content: |
          The PR has been registered in the Backstage catalog as:
          **component:pr-${{ parameters.owner }}-${{ parameters.repo }}-${{ parameters.branchName }}**
          
          You can now follow the PR's progress directly in Backstage!
