apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: open-pr-template
  title: Open Pull Request
  description: Opens a PR with a hello world file in any repository
  tags:
    - git
    - pr
spec:
  owner: platform-team
  type: service
  
  parameters:
    - title: Pull Request Information
      required:
        - username
        - owner
        - repo
        - prTitle
      properties:
        username:
          title: Your Username
          type: string
          description: Your GitHub/GitLab username
          ui:autofocus: true
        
        owner:
          title: Repository Owner
          type: string
          description: 'GitHub organization or username (e.g., r-reis)'
          ui:autofocus: true
          
        repo:
          title: Repository Name
          type: string
          description: 'Repository name (e.g., backstage-plugins)'
        
        prTitle:
          title: PR Title
          type: string
          default: 'Add hello world file'
        
        prDescription:
          title: PR Description
          type: string
          ui:widget: textarea
          default: 'This PR adds a hello world file'
          
        branchName:
          title: Branch Name
          type: string
          default: 'add-hello-world'

  steps:
    - id: fetch-base
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          username: ${{ parameters.username }}

    - id: publish
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=${{ parameters.owner }}&repo=${{ parameters.repo }}
        branchName: ${{ parameters.branchName }}
        title: ${{ parameters.prTitle }}
        description: ${{ parameters.prDescription }}
        gitAuthorName: ${{ parameters.username }}
        gitAuthorEmail: ${{ parameters.username }}@example.com

  output:
    links:
      - title: View Pull Request
        url: ${{ steps.publish.output.remoteUrl }}
